app:
    resource: "@AppBundle/Controller/"
    type:     annotation

places:
    type:     rest
    resource: AppBundle\Controller\PlacesController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
