services:
    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.password_encoder'

    app.user_provider:
        class: AppBundle\Security\UserProvider
        arguments:
            - '@doctrine.orm.entity_manager'

